DROP TABLE IF EXISTS trips;
DROP TABLE IS EXISTS user;

CREATE TABLE user (
    user id INTEGER PRIMARY KEY NOT NULL AUTOINCREMENT,
    fullname TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE trips (
    trip id INTEGER PRIMARY KEY NOT NULL AUTOINCREMENT,
    location TEXT NOT NULL,
    date INTEGER,
    description BLOB NOT NULL,
    badget INTEGER NOT NULL,
    user id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user id) REFERENCES user (user id)
);