DROP TABLE IF EXISTS trip;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS expense;
DROP TABLE IF EXISTS photo;

CREATE TABLE user (
    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
    fullname TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    email TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE trip (
    trip_id INTEGER PRIMARY KEY AUTOINCREMENT,
    destination TEXT NOT NULL,
    date TEXT,
    description TEXT NOT NULL,
    budget REAL,
    user_id INTEGER,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE
);

CREATE TABLE expense (
    expense_id INTEGER PRIMARY KEY AUTOINCREMENT,
    trip_id INTEGER,
    amount REAL NOT NULL,
    expense_description TEXT,
    expense_date TEXT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (trip_id) REFERENCES trip (trip_id) ON DELETE CASCADE
);

CREATE TABLE photo (
    photo_id INTEGER PRIMARY KEY AUTOINCREMENT,
    trip_id INTEGER,
    file_path TEXT REQUIRED NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (trip_id) REFERENCES trip (trip_id) ON DELETE CASCADE
);
